### ISSUE TITLE
SWAG github version

### ISSUE THREAD

**Issue by Annoneq** [dvize/SPT-TypeScript#1]
Error when choosing map causing game freeze

    TypeError: Cannot read properties of undefined (reading 'push')
    TypeError: Cannot read properties of undefined (reading 'push')
        at Function.genWaveStage2 (D:\Giereczki\EFT\user\mods\SWAG\src\SWAG.js:323:32)
        at Function.genWave (D:\Giereczki\EFT\user\mods\SWAG\src\SWAG.js:301:22)
        at Function.genWaveManager (D:\Giereczki\EFT\user\mods\SWAG\src\SWAG.js:157:22)
        at Function.configureMaps (D:\Giereczki\EFT\user\mods\SWAG\src\SWAG.js:120:26)
        at Object.action (D:\Giereczki\EFT\user\mods\SWAG\src\SWAG.js:31:26)
        at StaticRouterMod.handleStatic (C:\snapshot\project\obj\di\Router.js)
        at HttpRouter.handleRoute (C:\snapshot\project\obj\routers\HttpRouter.js)
        at HttpRouter.getResponse (C:\snapshot\project\obj\routers\HttpRouter.js)
        at AkiHttpListener.getResponse (C:\snapshot\project\obj\servers\http\AkiHttpListener.js)
        at AkiHttpListener.handle (C:\snapshot\project\obj\servers\http\AkiHttpListener.js)
    TypeError: Cannot read properties of undefined (reading 'push')
    TypeError: Cannot read properties of undefined (reading 'push')
        at Function.genWaveStage2 (D:\Giereczki\EFT\user\mods\SWAG\src\SWAG.js:323:32)
        at Function.genWave (D:\Giereczki\EFT\user\mods\SWAG\src\SWAG.js:301:22)
        at Function.genWaveManager (D:\Giereczki\EFT\user\mods\SWAG\src\SWAG.js:157:22)
        at Function.configureMaps (D:\Giereczki\EFT\user\mods\SWAG\src\SWAG.js:120:26)
        at Object.action (D:\Giereczki\EFT\user\mods\SWAG\src\SWAG.js:31:26)
        at StaticRouterMod.handleStatic (C:\snapshot\project\obj\di\Router.js)
        at HttpRouter.handleRoute (C:\snapshot\project\obj\routers\HttpRouter.js)
        at HttpRouter.getResponse (C:\snapshot\project\obj\routers\HttpRouter.js)
        at AkiHttpListener.getResponse (C:\snapshot\project\obj\servers\http\AkiHttpListener.js)
        at AkiHttpListener.handle (C:\snapshot\project\obj\servers\http\AkiHttpListener.js)

**Comment by dvize** [comment]
the code is incomplete.  it is being worked on.
